tests: add true/false/contains/doesNotCointain assertions
monte-language/typhon pull request #147
Opened 2016-12-18 08:05 UTC by justinnoah

2016-12-18 08:26 UTC, MostAwesomeDude approved these changes
LGTM

2016-12-20 00:19 UTC, dckc requested changes

2016-12-20 00:19 UTC, dckc commented on mast/testRunner.mt
> +                    if (o._respondsTo("contains", 1)):
why bother with the `o._respondsTo("contains", 1)` checks?

If `o.contains(k)` throws `refused`, that's a bug that should be reported as such, no? Why change it to `assert.fail()`?

2017-03-25 17:41 UTC, MostAwesomeDude commented on mast/testRunner.mt
> +                    if (o._respondsTo("contains", 1)):
It allows for error message customization. Pretty much all of these methods are about customized errors and easier-to-read testing flows.

2025-01-01 04:03 UTC, closed without merging